### ISSUE TITLE
Grammatical errors in German translation

### ISSUE THREAD

**Issue by tyrann0us** [brightnucleus/custom-content#10]
In the string `Choose from the most used %4$s`, the placeholder is replaced with the lowercase taxonomy label. For a taxonomy named "Difficulty level" (German "Schwierigkeitsgrad"), this will result in the following German translation:
>Aus meistverwendeten schwierigkeitsgrade auswählen

A lowercase label works in English, but it should be uppercase in German (`Schwierigkeitsgrade`).

Additionally, it should be `Schwierigkeitsgraden`:
>Wähle aus den meistgenutzten Schwierigkeitsgraden

(German translation reworded based on #9.)

I guess that the latter is not (easily) possible.

**Comment by schlessera** [comment]
The entire translation layer used with the 4 different versions of a noun really is an over-simplification for convenience. For some languages, that might not be enough, and this is a known limitation. In such a case, you are supposed to override the default strings that use these noun forms and rather provide the entire translated message instead.

**Comment by tyrann0us** [comment]
Hi @schlessera, thanks for your quick feedback. You are right, in certain cases it is grammatically necessary to specify some or all labels.

I noticed the problem with an existing implementation and didn't check in more detail, sorry.
