### ISSUE TITLE
Fatal error: Uncaught TypeError when trying to register a CPT.

### ISSUE THREAD

**Issue by tzimpel** [brightnucleus/custom-content#2]
Using the example code to register a custom post type in WordPress from the `README.md`, I get the following error:

`Fatal error: Uncaught TypeError: Argument 2 passed to BrightNucleus\CustomContent\CustomPostType::prepareArguments() must be of the type array, string given, called in `[...]`/wp-content/plugins/contact-form-7-shortcode-enabler/vendor/brightnucleus/custom-content/src/AbstractContentType.php on line 122 and defined in `[...]`/wp-content/plugins/contact-form-7-shortcode-enabler/vendor/brightnucleus/custom-content/src/CustomPostType.php on line 56`

Seemingly `do_action('init);` results in `CustomPostType::register()` being called with `$args = ''`, which results In `CustomPostType::prepareArguments()` being called with a string instead of an array as expected.

**Comment by tzimpel** [comment]
Hi again, did you find the time to look into this issue? Can I provide additional information to help you? Thanks in advance!

**Comment by schlessera** [comment]
Hi @tzimpel,

Thanks for the report and you patience.

I fixed this in release v0.1.6, which should be available in a minute or two through packagist.

**Comment by tzimpel** [comment]
Hi @schlessera,

thanks for the fix - that should indeed do the trick :-)
