### ISSUE TITLE
Add "template" and "template_lock" as constants to Argument class?

### ISSUE THREAD

**Issue by tyrann0us** [brightnucleus/custom-content#3]
The class constants in [`Argument`](https://github.com/brightnucleus/custom-content/blob/56015155335e31261e408be1bd6e67bd1f7d1033/src/CustomPostType/Argument.php) are taken from [`register_post_type()`](https://github.com/WordPress/WordPress/blob/6fd8080e7ee7599b36d4528f72a8ced612130b8c/wp-includes/post.php#L1125-L1298).

With WordPress 5.0, two new arguments were introduced: `template` and `template_lock` (see https://developer.wordpress.org/block-editor/developers/block-api/block-templates/#custom-post-types and https://github.com/WordPress/WordPress/blob/6fcd28170794db7675485c55cf1eb123f5297d33/wp-admin/edit-form-blocks.php#L314-L317. They allow developers to define "block templates" i.e. lists of (nested) block items that should be "preselected" for posts of the given post type.

Although they are not documented/mentioned in the Codex link mentioned above, I still think they should be added to the list of class constants:
```
const TEMPLATE              = 'template';
const TEMPLATE_LOCK         = 'template_lock';
```

What do you think? I'm happy to provide a PR.
Thanks!

**Comment by schlessera** [comment]
Yes, sounds good, I'll gladly accept a PR.
