### ISSUE TITLE
`show_in_rest` is missing in `CustomTaxonomy\Argument`

### ISSUE THREAD

**Issue by tzimpel** [brightnucleus/custom-content#5]
Hi Alain,

the constant
`const SHOW_IN_REST          = 'show_in_rest';`
is present as argument for custom post types, but not for custom taxonomies. It's needed to make taxonomies available in Gutenberg.

Will provide a PR.

**Comment by schlessera** [comment]
Release `v0.1.7` was tagged with this release and should be available via packagist shortly...

**Comment by tzimpel** [comment]
Thanks a lot for the quick reaction.
