### ISSUE TITLE
German translation differ from core

### ISSUE THREAD

**Issue by tyrann0us** [brightnucleus/custom-content#9]
Hi!

At least one German translation differs from core.

Core:
>Wähle aus den meistgenutzten Schlagwörtern

(https://translate.wordpress.org/projects/wp/dev/de/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7919&filters%5Btranslation_id%5D=45508086)

Custom Content:
https://github.com/brightnucleus/custom-content/blob/75e1a7cfb909dc86cf5ccd672761937a20d5b7ee/languages/bn-custom-content-de_DE.po#L332

I have not checked any other translation to see if they differ from core. If I find time, I will, and ideally prepare a PR.

**Comment by schlessera** [comment]
Fixed in v0.1.9
